language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - "node_modules"
before_script:
  - yarn
script: 
  - yarn generate
  - cp dist docs
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  target-branch: master
  local-dir: dist
  on:
    branch: development