language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - "node_modules"
before_script:
  - yarn
script: 
  - yarn generate
  - rm -rf docs
  - mv dist docs
deploy:
  provider: script
  skip-cleanup: true
  keep-history: true
  script: bash push.sh
  on:
    branch: master